# Triggers
# This pipeline will be triggered manually for a release or by github comment
trigger: none
pr:
  autoCancel: false
  branches:
    include:
      - '*'

jobs:
  - template: 'templates/jobs/acceptance_namespace_rbac_jobs.yaml'


